@hostname = http://localhost:8000
@authToken = {{login.response.body.$.access}}
###

# @name login
POST {{hostname}}/api/token/ HTTP/1.1
Content-Type: application/json

{
    "username": "admin",
    "password": "test"
}

###

# @name refreshToken
POST {{hostname}}/api/token/refresh/ HTTP/1.1
Content-Type: application/json

{
    "refresh": "{{login.response.body.$.refresh}}"
}

###

@authToken = {{refreshToken.response.body.$.access}}

###

# @name products
GET {{hostname}}/api/products HTTP/1.1

###

POST {{hostname}}/api/products/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "name": "Macbook Pro",
    "description": "A high-performance laptop",
    "price": 1299.99,
    "stock": 10
}

###

GET {{hostname}}/api/products/11/ HTTP/1.1

###

PUT {{hostname}}/api/products/11/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "name": "Macbook Pro",
    "description": "A high-performance laptop",
    "price": 1299.99,
    "stock": 10
}

###

DELETE {{hostname}}/api/products/11/ HTTP/1.1
Authorization: Bearer {{authToken}}

###

GET {{hostname}}/api/products/info/ HTTP/1.1

###

# @name orders

GET {{hostname}}/api/orders HTTP/1.1

###

GET {{hostname}}/api/user-orders HTTP/1.1
Authorization: Bearer {{authToken}}